name: owmflutter
description: Unofficial wykop.pl client.

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.19.0
  pref_gen_annotations: ^0.0.2
  pref_gen_flutter: ^0.0.3
  built_collection: ^4.3.2
  shared_preferences: ^0.5.6+3
  built_value: ^7.0.9
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  image_picker: ^0.6.3+4
  flutter_advanced_networkimage: ^0.7.0
  video_player: ^0.10.8+1
  path_provider: ^1.6.5
  timeago: ^2.0.26
  font_awesome_flutter: ^8.7.0
  photo_view: ^0.9.2
  share: ^0.6.3+6
  font_awesome: ^5.10.1
  provider: ^4.0.4
  intl: ^0.16.1
  flutter_material_color_picker: ^1.0.5
  esys_flutter_share: ^1.0.2
  mime: ^0.9.6+3
  image_downloader: ^0.19.2
  async: ^2.4.0
  background_fetch: ^0.5.4
  flutter_local_notifications: ^1.3.0
  youtube_player_flutter: ^6.1.0+4
  flutter_custom_tabs: ^0.6.0
  community_material_icon: ^3.5.95
  vibration: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  pref_gen: ^0.0.3
  build_runner: ^1.8.0
  built_value_generator: ^7.0.9

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#ff5f98f4"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: OWMGlyphs
      fonts:
        - asset: assets/fonts/OWMGlyphs.ttf
  assets:
    - secrets.json
    - rogal.png
    - kosmo_bg.png
    - avatar.png
    - app_icon.png
    - no_picture.jpg
    - no_picture_night.jpg
